"""rename_uuid_to_id

Revision ID: 94ce693d92c6
Revises: 82250724b2c4
Create Date: 2025-12-09 14:16:34.521602

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94ce693d92c6'
down_revision: Union[str, None] = '82250724b2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')

    # 1. Add 'id' columns first
    op.add_column('tier', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('user', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('post', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('rate_limit', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))

    # 1.1 Drop foreign keys that reference the old 'uuid' columns (which are also PKs)
    # This is necessary because we cannot drop PKs if they are referenced by FKs.
    op.drop_constraint(op.f('post_created_by_user_id_fkey'), 'post', type_='foreignkey')
    op.drop_constraint(op.f('rate_limit_tier_id_fkey'), 'rate_limit', type_='foreignkey')
    op.drop_constraint(op.f('user_tier_id_fkey'), 'user', type_='foreignkey')

    # 2. Add Primary Key constraints on 'id'
    op.drop_constraint('tier_pkey', 'tier', type_='primary')
    op.create_primary_key('tier_pkey', 'tier', ['id'])

    op.drop_constraint('user_pkey', 'user', type_='primary')
    op.create_primary_key('user_pkey', 'user', ['id'])

    op.drop_constraint('post_pkey', 'post', type_='primary')
    op.create_primary_key('post_pkey', 'post', ['id'])

    op.drop_constraint('rate_limit_pkey', 'rate_limit', type_='primary')
    op.create_primary_key('rate_limit_pkey', 'rate_limit', ['id'])


    # 3. Re-create Foreign Keys to point to new 'id' columns
    op.create_foreign_key(None, 'post', 'user', ['created_by_user_id'], ['id'])
    op.create_foreign_key(None, 'rate_limit', 'tier', ['tier_id'], ['id'])
    op.create_foreign_key(None, 'user', 'tier', ['tier_id'], ['id'])

    # 4. Drop old 'uuid' columns
    op.drop_column('post', 'uuid')
    op.drop_column('rate_limit', 'uuid')
    op.drop_column('tier', 'uuid')
    op.drop_column('user', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_tier_id_fkey'), 'user', 'tier', ['tier_id'], ['uuid'])
    op.drop_column('user', 'id')
    op.add_column('tier', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_column('tier', 'id')
    op.add_column('rate_limit', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rate_limit', type_='foreignkey')
    op.create_foreign_key(op.f('rate_limit_tier_id_fkey'), 'rate_limit', 'tier', ['tier_id'], ['uuid'])
    op.drop_column('rate_limit', 'id')
    op.add_column('post', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(op.f('post_created_by_user_id_fkey'), 'post', 'user', ['created_by_user_id'], ['uuid'])
    op.drop_column('post', 'id')
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    # ### end Alembic commands ###
